FROM node:22-alpine3.19

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

COPY dist /home/node/app/dist
COPY yarn.lock /home/node/app/yarn.lock
# COPY .env.production /home/node/app/.env.production
COPY package.json /home/node/app/package.json

WORKDIR /home/node/app

RUN yarn install --production

CMD ["yarn", "start:prod"]
