export const PRODUCTO_RELATIONS = [
  'categoria',
  //'idEtiquetas',
  'planta',
  'accesorio',
  'macetero',
  'insumo',
  // 'planta.especie',
  'planta.fotoPeriodo',
  'planta.entorno',
  'planta.toleranciaTemperatura',
  'planta.iluminacion',
  'planta.tamano',
  'planta.habitoCrecimiento',
  'planta.tipoRiego',
  'planta.color',
  'accesorio.color',
  'accesorio.tipoAccesorio',
  'accesorio.marca',
  'insumo.tipoInsumo',
  'insumo.marca',
  'macetero.tipoMacetero',
  'macetero.marca',
];
